spring.datasource.url=jdbc:mysql://employee-mysql-server.mysql.database.azure.com:3306/employeedb?useSSL=true
spring.datasource.username=mysqlems

spring.datasource.password=employee123@


spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.jpa.show-sql=true

spring.thymeleaf.cache=false
